#!/usr/bin/env python3
#coding: utf-8

import sys
import os
import re
import subprocess
from unicodedata import normalize

if len(sys.argv) == 1:
    print("Informe uma string ou arquivo válido!")
    print("$ unicode <string|file>")
    exit(0)

file = sys.argv[1]

def install(name):
    subprocess.call(['pip3', 'install', name])


# install("unidecode")
# install("sqlparse")


######
#  Removendo caractéres espéciais
######


def unicodeASCII(string):
    string = string.upper()
    string = normalize('NFKD', string).encode("ASCII", "ignore").decode("ASCII")
    # Remover
    string = re.sub(u"[\.()%!\?\^\\\/#$]", '', string)
    # Remover espaços duplos
    string = re.sub(u" {2,}", ' ', string)
    # Remover espaços no inicio e no final
    string = string.strip()
    # Substituir por _
    string = re.sub(u"[ -]", '_', string)
    return string


if os.path.exists(file):
    # Arquivo existe
    print("Ler arquivo")
else:
    # Arquivo não existe
    print(unicodeASCII(file))
