#!/usr/bin/env python3
#coding: utf-8

# Doc 
# https://buildmedia.readthedocs.org/media/pdf/sqlparse/latest/sqlparse.pdf

import sqlparse
import subprocess
import re
import sqlparse

def install(name):
    subprocess.call(['pip3', 'install', name])

# install("sqlparse")


######
#  Replace in dicionário 
######
dic = [
    
]
sql = '''
select empcod, codemp, emp.nome as codemp, codempresa, codempresa as empresa from empresa emp;
select empcod, codemp, emp.nome as codemp, codempresa, codempresa as empresa from empresa emp
'''

# Separar mais de uma consulta em segmentos
statements = sqlparse.split(sql)

# Formart sql
# print(sqlparse.format(statements[0], reindent=True, keyword_case='upper'))

parsed = sqlparse.parse(sql)

for token in parsed[0].flatten():
    print(token)
